/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MetaNodeStakeInterface extends utils.Interface {
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "ETH_PID()": FunctionFragment;
    "MetaNode()": FunctionFragment;
    "MetaNodePerBlock()": FunctionFragment;
    "UPGRADE_INTERFACE_VERSION()": FunctionFragment;
    "UPGRADE_ROLE()": FunctionFragment;
    "addPool(address,uint256,uint256,uint256,bool)": FunctionFragment;
    "claim(uint256)": FunctionFragment;
    "claimPaused()": FunctionFragment;
    "deposit(uint256,uint256)": FunctionFragment;
    "depositETH()": FunctionFragment;
    "endBlock()": FunctionFragment;
    "getMultiplier(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address,uint256,uint256,uint256)": FunctionFragment;
    "massUpdatePools()": FunctionFragment;
    "pauseClaim()": FunctionFragment;
    "pauseWithdraw()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingMetaNode(uint256,address)": FunctionFragment;
    "pendingMetaNodeByBlockNumber(uint256,address,uint256)": FunctionFragment;
    "pool(uint256)": FunctionFragment;
    "poolLength()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setEndBlock(uint256)": FunctionFragment;
    "setMetaNode(address)": FunctionFragment;
    "setMetaNodePerBlock(uint256)": FunctionFragment;
    "setPoolWeight(uint256,uint256,bool)": FunctionFragment;
    "setStartBlock(uint256)": FunctionFragment;
    "stakingBalance(uint256,address)": FunctionFragment;
    "startBlock()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "totalPoolWeight()": FunctionFragment;
    "unpauseClaim()": FunctionFragment;
    "unpauseWithdraw()": FunctionFragment;
    "unstake(uint256,uint256)": FunctionFragment;
    "updatePool(uint256)": FunctionFragment;
    "updatePool(uint256,uint256,uint256)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "user(uint256,address)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "withdrawAmount(uint256,address)": FunctionFragment;
    "withdrawPaused()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "ETH_PID"
      | "MetaNode"
      | "MetaNodePerBlock"
      | "UPGRADE_INTERFACE_VERSION"
      | "UPGRADE_ROLE"
      | "addPool"
      | "claim"
      | "claimPaused"
      | "deposit"
      | "depositETH"
      | "endBlock"
      | "getMultiplier"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "massUpdatePools"
      | "pauseClaim"
      | "pauseWithdraw"
      | "paused"
      | "pendingMetaNode"
      | "pendingMetaNodeByBlockNumber"
      | "pool"
      | "poolLength"
      | "proxiableUUID"
      | "renounceRole"
      | "revokeRole"
      | "setEndBlock"
      | "setMetaNode"
      | "setMetaNodePerBlock"
      | "setPoolWeight"
      | "setStartBlock"
      | "stakingBalance"
      | "startBlock"
      | "supportsInterface"
      | "totalPoolWeight"
      | "unpauseClaim"
      | "unpauseWithdraw"
      | "unstake"
      | "updatePool(uint256)"
      | "updatePool(uint256,uint256,uint256)"
      | "upgradeToAndCall"
      | "user"
      | "withdraw"
      | "withdrawAmount"
      | "withdrawPaused"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH_PID", values?: undefined): string;
  encodeFunctionData(functionFragment: "MetaNode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MetaNodePerBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "endBlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMultiplier",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "massUpdatePools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pauseClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pauseWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingMetaNode",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMetaNodeByBlockNumber",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pool",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "poolLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setEndBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetaNode",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetaNodePerBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolWeight",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setStartBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingBalance",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "startBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePool(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePool(uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "user",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAmount",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPaused",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH_PID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MetaNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MetaNodePerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "massUpdatePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingMetaNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMetaNodeByBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolLength", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEndBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetaNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetaNodePerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePool(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePool(uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "user", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPaused",
    data: BytesLike
  ): Result;

  events: {
    "AddPool(address,uint256,uint256,uint256,uint256)": EventFragment;
    "Claim(address,uint256,uint256)": EventFragment;
    "Deposit(address,uint256,uint256)": EventFragment;
    "Initialized(uint64)": EventFragment;
    "PauseClaim()": EventFragment;
    "PauseWithdraw()": EventFragment;
    "Paused(address)": EventFragment;
    "RequestUnstake(address,uint256,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SetEndBlock(uint256)": EventFragment;
    "SetMetaNode(address)": EventFragment;
    "SetMetaNodePerBlock(uint256)": EventFragment;
    "SetPoolWeight(uint256,uint256,uint256)": EventFragment;
    "SetStartBlock(uint256)": EventFragment;
    "UnpauseClaim()": EventFragment;
    "UnpauseWithdraw()": EventFragment;
    "Unpaused(address)": EventFragment;
    "UpdatePool(uint256,uint256,uint256)": EventFragment;
    "UpdatePoolInfo(uint256,uint256,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
    "Withdraw(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauseClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauseWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestUnstake"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetEndBlock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMetaNode"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMetaNodePerBlock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetPoolWeight"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetStartBlock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnpauseClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnpauseWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatePool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdatePoolInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface AddPoolEventObject {
  stTokenAddress: string;
  poolWeight: BigNumber;
  lastRewardBlock: BigNumber;
  minDepositAmount: BigNumber;
  unstakeLockedBlocks: BigNumber;
}
export type AddPoolEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  AddPoolEventObject
>;

export type AddPoolEventFilter = TypedEventFilter<AddPoolEvent>;

export interface ClaimEventObject {
  user: string;
  poolId: BigNumber;
  MetaNodeReward: BigNumber;
}
export type ClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ClaimEventObject
>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface DepositEventObject {
  user: string;
  poolId: BigNumber;
  amount: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PauseClaimEventObject {}
export type PauseClaimEvent = TypedEvent<[], PauseClaimEventObject>;

export type PauseClaimEventFilter = TypedEventFilter<PauseClaimEvent>;

export interface PauseWithdrawEventObject {}
export type PauseWithdrawEvent = TypedEvent<[], PauseWithdrawEventObject>;

export type PauseWithdrawEventFilter = TypedEventFilter<PauseWithdrawEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RequestUnstakeEventObject {
  user: string;
  poolId: BigNumber;
  amount: BigNumber;
}
export type RequestUnstakeEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  RequestUnstakeEventObject
>;

export type RequestUnstakeEventFilter = TypedEventFilter<RequestUnstakeEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface SetEndBlockEventObject {
  endBlock: BigNumber;
}
export type SetEndBlockEvent = TypedEvent<[BigNumber], SetEndBlockEventObject>;

export type SetEndBlockEventFilter = TypedEventFilter<SetEndBlockEvent>;

export interface SetMetaNodeEventObject {
  MetaNode: string;
}
export type SetMetaNodeEvent = TypedEvent<[string], SetMetaNodeEventObject>;

export type SetMetaNodeEventFilter = TypedEventFilter<SetMetaNodeEvent>;

export interface SetMetaNodePerBlockEventObject {
  MetaNodePerBlock: BigNumber;
}
export type SetMetaNodePerBlockEvent = TypedEvent<
  [BigNumber],
  SetMetaNodePerBlockEventObject
>;

export type SetMetaNodePerBlockEventFilter =
  TypedEventFilter<SetMetaNodePerBlockEvent>;

export interface SetPoolWeightEventObject {
  poolId: BigNumber;
  poolWeight: BigNumber;
  totalPoolWeight: BigNumber;
}
export type SetPoolWeightEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  SetPoolWeightEventObject
>;

export type SetPoolWeightEventFilter = TypedEventFilter<SetPoolWeightEvent>;

export interface SetStartBlockEventObject {
  startBlock: BigNumber;
}
export type SetStartBlockEvent = TypedEvent<
  [BigNumber],
  SetStartBlockEventObject
>;

export type SetStartBlockEventFilter = TypedEventFilter<SetStartBlockEvent>;

export interface UnpauseClaimEventObject {}
export type UnpauseClaimEvent = TypedEvent<[], UnpauseClaimEventObject>;

export type UnpauseClaimEventFilter = TypedEventFilter<UnpauseClaimEvent>;

export interface UnpauseWithdrawEventObject {}
export type UnpauseWithdrawEvent = TypedEvent<[], UnpauseWithdrawEventObject>;

export type UnpauseWithdrawEventFilter = TypedEventFilter<UnpauseWithdrawEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UpdatePoolEventObject {
  poolId: BigNumber;
  lastRewardBlock: BigNumber;
  totalMetaNode: BigNumber;
}
export type UpdatePoolEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  UpdatePoolEventObject
>;

export type UpdatePoolEventFilter = TypedEventFilter<UpdatePoolEvent>;

export interface UpdatePoolInfoEventObject {
  poolId: BigNumber;
  minDepositAmount: BigNumber;
  unstakeLockedBlocks: BigNumber;
}
export type UpdatePoolInfoEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  UpdatePoolInfoEventObject
>;

export type UpdatePoolInfoEventFilter = TypedEventFilter<UpdatePoolInfoEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface WithdrawEventObject {
  user: string;
  poolId: BigNumber;
  amount: BigNumber;
  blockNumber: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface MetaNodeStake extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MetaNodeStakeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    ETH_PID(overrides?: CallOverrides): Promise<[BigNumber]>;

    MetaNode(overrides?: CallOverrides): Promise<[string]>;

    MetaNodePerBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<[string]>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    addPool(
      _stTokenAddress: PromiseOrValue<string>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claim(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimPaused(overrides?: CallOverrides): Promise<[boolean]>;

    deposit(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    endBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMultiplier(
      _from: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { multiplier: BigNumber }>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _MetaNode: PromiseOrValue<string>,
      _startBlock: PromiseOrValue<BigNumberish>,
      _endBlock: PromiseOrValue<BigNumberish>,
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    massUpdatePools(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingMetaNode(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingMetaNodeByBlockNumber(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pool(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stTokenAddress: string;
        poolWeight: BigNumber;
        lastRewardBlock: BigNumber;
        accMetaNodePerST: BigNumber;
        stTokenAmount: BigNumber;
        minDepositAmount: BigNumber;
        unstakeLockedBlocks: BigNumber;
      }
    >;

    poolLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setEndBlock(
      _endBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMetaNode(
      _MetaNode: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMetaNodePerBlock(
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPoolWeight(
      _pid: PromiseOrValue<BigNumberish>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStartBlock(
      _startBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakingBalance(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    startBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    totalPoolWeight(overrides?: CallOverrides): Promise<[BigNumber]>;

    unpauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unstake(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "updatePool(uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "updatePool(uint256,uint256,uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    user(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        stAmount: BigNumber;
        finishedMetaNode: BigNumber;
        pendingMetaNode: BigNumber;
      }
    >;

    withdraw(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawAmount(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        requestAmount: BigNumber;
        pendingWithdrawAmount: BigNumber;
      }
    >;

    withdrawPaused(overrides?: CallOverrides): Promise<[boolean]>;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  ETH_PID(overrides?: CallOverrides): Promise<BigNumber>;

  MetaNode(overrides?: CallOverrides): Promise<string>;

  MetaNodePerBlock(overrides?: CallOverrides): Promise<BigNumber>;

  UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

  UPGRADE_ROLE(overrides?: CallOverrides): Promise<string>;

  addPool(
    _stTokenAddress: PromiseOrValue<string>,
    _poolWeight: PromiseOrValue<BigNumberish>,
    _minDepositAmount: PromiseOrValue<BigNumberish>,
    _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
    _withUpdate: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claim(
    _pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimPaused(overrides?: CallOverrides): Promise<boolean>;

  deposit(
    _pid: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositETH(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  endBlock(overrides?: CallOverrides): Promise<BigNumber>;

  getMultiplier(
    _from: PromiseOrValue<BigNumberish>,
    _to: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _MetaNode: PromiseOrValue<string>,
    _startBlock: PromiseOrValue<BigNumberish>,
    _endBlock: PromiseOrValue<BigNumberish>,
    _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  massUpdatePools(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pauseClaim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pauseWithdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingMetaNode(
    _pid: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pendingMetaNodeByBlockNumber(
    _pid: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    _blockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pool(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      stTokenAddress: string;
      poolWeight: BigNumber;
      lastRewardBlock: BigNumber;
      accMetaNodePerST: BigNumber;
      stTokenAmount: BigNumber;
      minDepositAmount: BigNumber;
      unstakeLockedBlocks: BigNumber;
    }
  >;

  poolLength(overrides?: CallOverrides): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    callerConfirmation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setEndBlock(
    _endBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMetaNode(
    _MetaNode: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMetaNodePerBlock(
    _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPoolWeight(
    _pid: PromiseOrValue<BigNumberish>,
    _poolWeight: PromiseOrValue<BigNumberish>,
    _withUpdate: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStartBlock(
    _startBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakingBalance(
    _pid: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  startBlock(overrides?: CallOverrides): Promise<BigNumber>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  totalPoolWeight(overrides?: CallOverrides): Promise<BigNumber>;

  unpauseClaim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpauseWithdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unstake(
    _pid: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "updatePool(uint256)"(
    _pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "updatePool(uint256,uint256,uint256)"(
    _pid: PromiseOrValue<BigNumberish>,
    _minDepositAmount: PromiseOrValue<BigNumberish>,
    _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  user(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      stAmount: BigNumber;
      finishedMetaNode: BigNumber;
      pendingMetaNode: BigNumber;
    }
  >;

  withdraw(
    _pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawAmount(
    _pid: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      requestAmount: BigNumber;
      pendingWithdrawAmount: BigNumber;
    }
  >;

  withdrawPaused(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    ETH_PID(overrides?: CallOverrides): Promise<BigNumber>;

    MetaNode(overrides?: CallOverrides): Promise<string>;

    MetaNodePerBlock(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<string>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<string>;

    addPool(
      _stTokenAddress: PromiseOrValue<string>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    claim(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimPaused(overrides?: CallOverrides): Promise<boolean>;

    deposit(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositETH(overrides?: CallOverrides): Promise<void>;

    endBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getMultiplier(
      _from: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _MetaNode: PromiseOrValue<string>,
      _startBlock: PromiseOrValue<BigNumberish>,
      _endBlock: PromiseOrValue<BigNumberish>,
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    massUpdatePools(overrides?: CallOverrides): Promise<void>;

    pauseClaim(overrides?: CallOverrides): Promise<void>;

    pauseWithdraw(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingMetaNode(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingMetaNodeByBlockNumber(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pool(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        stTokenAddress: string;
        poolWeight: BigNumber;
        lastRewardBlock: BigNumber;
        accMetaNodePerST: BigNumber;
        stTokenAmount: BigNumber;
        minDepositAmount: BigNumber;
        unstakeLockedBlocks: BigNumber;
      }
    >;

    poolLength(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setEndBlock(
      _endBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetaNode(
      _MetaNode: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetaNodePerBlock(
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolWeight(
      _pid: PromiseOrValue<BigNumberish>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStartBlock(
      _startBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakingBalance(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBlock(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalPoolWeight(overrides?: CallOverrides): Promise<BigNumber>;

    unpauseClaim(overrides?: CallOverrides): Promise<void>;

    unpauseWithdraw(overrides?: CallOverrides): Promise<void>;

    unstake(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "updatePool(uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "updatePool(uint256,uint256,uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    user(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        stAmount: BigNumber;
        finishedMetaNode: BigNumber;
        pendingMetaNode: BigNumber;
      }
    >;

    withdraw(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAmount(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        requestAmount: BigNumber;
        pendingWithdrawAmount: BigNumber;
      }
    >;

    withdrawPaused(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AddPool(address,uint256,uint256,uint256,uint256)"(
      stTokenAddress?: PromiseOrValue<string> | null,
      poolWeight?: PromiseOrValue<BigNumberish> | null,
      lastRewardBlock?: PromiseOrValue<BigNumberish> | null,
      minDepositAmount?: null,
      unstakeLockedBlocks?: null
    ): AddPoolEventFilter;
    AddPool(
      stTokenAddress?: PromiseOrValue<string> | null,
      poolWeight?: PromiseOrValue<BigNumberish> | null,
      lastRewardBlock?: PromiseOrValue<BigNumberish> | null,
      minDepositAmount?: null,
      unstakeLockedBlocks?: null
    ): AddPoolEventFilter;

    "Claim(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      MetaNodeReward?: null
    ): ClaimEventFilter;
    Claim(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      MetaNodeReward?: null
    ): ClaimEventFilter;

    "Deposit(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositEventFilter;
    Deposit(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "PauseClaim()"(): PauseClaimEventFilter;
    PauseClaim(): PauseClaimEventFilter;

    "PauseWithdraw()"(): PauseWithdrawEventFilter;
    PauseWithdraw(): PauseWithdrawEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RequestUnstake(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): RequestUnstakeEventFilter;
    RequestUnstake(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): RequestUnstakeEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "SetEndBlock(uint256)"(
      endBlock?: PromiseOrValue<BigNumberish> | null
    ): SetEndBlockEventFilter;
    SetEndBlock(
      endBlock?: PromiseOrValue<BigNumberish> | null
    ): SetEndBlockEventFilter;

    "SetMetaNode(address)"(
      MetaNode?: PromiseOrValue<string> | null
    ): SetMetaNodeEventFilter;
    SetMetaNode(
      MetaNode?: PromiseOrValue<string> | null
    ): SetMetaNodeEventFilter;

    "SetMetaNodePerBlock(uint256)"(
      MetaNodePerBlock?: PromiseOrValue<BigNumberish> | null
    ): SetMetaNodePerBlockEventFilter;
    SetMetaNodePerBlock(
      MetaNodePerBlock?: PromiseOrValue<BigNumberish> | null
    ): SetMetaNodePerBlockEventFilter;

    "SetPoolWeight(uint256,uint256,uint256)"(
      poolId?: PromiseOrValue<BigNumberish> | null,
      poolWeight?: PromiseOrValue<BigNumberish> | null,
      totalPoolWeight?: null
    ): SetPoolWeightEventFilter;
    SetPoolWeight(
      poolId?: PromiseOrValue<BigNumberish> | null,
      poolWeight?: PromiseOrValue<BigNumberish> | null,
      totalPoolWeight?: null
    ): SetPoolWeightEventFilter;

    "SetStartBlock(uint256)"(
      startBlock?: PromiseOrValue<BigNumberish> | null
    ): SetStartBlockEventFilter;
    SetStartBlock(
      startBlock?: PromiseOrValue<BigNumberish> | null
    ): SetStartBlockEventFilter;

    "UnpauseClaim()"(): UnpauseClaimEventFilter;
    UnpauseClaim(): UnpauseClaimEventFilter;

    "UnpauseWithdraw()"(): UnpauseWithdrawEventFilter;
    UnpauseWithdraw(): UnpauseWithdrawEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "UpdatePool(uint256,uint256,uint256)"(
      poolId?: PromiseOrValue<BigNumberish> | null,
      lastRewardBlock?: PromiseOrValue<BigNumberish> | null,
      totalMetaNode?: null
    ): UpdatePoolEventFilter;
    UpdatePool(
      poolId?: PromiseOrValue<BigNumberish> | null,
      lastRewardBlock?: PromiseOrValue<BigNumberish> | null,
      totalMetaNode?: null
    ): UpdatePoolEventFilter;

    "UpdatePoolInfo(uint256,uint256,uint256)"(
      poolId?: PromiseOrValue<BigNumberish> | null,
      minDepositAmount?: PromiseOrValue<BigNumberish> | null,
      unstakeLockedBlocks?: PromiseOrValue<BigNumberish> | null
    ): UpdatePoolInfoEventFilter;
    UpdatePoolInfo(
      poolId?: PromiseOrValue<BigNumberish> | null,
      minDepositAmount?: PromiseOrValue<BigNumberish> | null,
      unstakeLockedBlocks?: PromiseOrValue<BigNumberish> | null
    ): UpdatePoolInfoEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;

    "Withdraw(address,uint256,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      blockNumber?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;
    Withdraw(
      user?: PromiseOrValue<string> | null,
      poolId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      blockNumber?: PromiseOrValue<BigNumberish> | null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    ETH_PID(overrides?: CallOverrides): Promise<BigNumber>;

    MetaNode(overrides?: CallOverrides): Promise<BigNumber>;

    MetaNodePerBlock(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_INTERFACE_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    addPool(
      _stTokenAddress: PromiseOrValue<string>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claim(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimPaused(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    endBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getMultiplier(
      _from: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _MetaNode: PromiseOrValue<string>,
      _startBlock: PromiseOrValue<BigNumberish>,
      _endBlock: PromiseOrValue<BigNumberish>,
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    massUpdatePools(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingMetaNode(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingMetaNodeByBlockNumber(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pool(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolLength(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setEndBlock(
      _endBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMetaNode(
      _MetaNode: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMetaNodePerBlock(
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPoolWeight(
      _pid: PromiseOrValue<BigNumberish>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStartBlock(
      _startBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakingBalance(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBlock(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalPoolWeight(overrides?: CallOverrides): Promise<BigNumber>;

    unpauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unstake(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "updatePool(uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "updatePool(uint256,uint256,uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    user(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawAmount(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawPaused(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ETH_PID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MetaNode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MetaNodePerBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UPGRADE_INTERFACE_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    UPGRADE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addPool(
      _stTokenAddress: PromiseOrValue<string>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claim(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    endBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMultiplier(
      _from: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _MetaNode: PromiseOrValue<string>,
      _startBlock: PromiseOrValue<BigNumberish>,
      _endBlock: PromiseOrValue<BigNumberish>,
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    massUpdatePools(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingMetaNode(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingMetaNodeByBlockNumber(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      _blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pool(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      callerConfirmation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setEndBlock(
      _endBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMetaNode(
      _MetaNode: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMetaNodePerBlock(
      _MetaNodePerBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPoolWeight(
      _pid: PromiseOrValue<BigNumberish>,
      _poolWeight: PromiseOrValue<BigNumberish>,
      _withUpdate: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStartBlock(
      _startBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakingBalance(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    startBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalPoolWeight(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpauseClaim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpauseWithdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unstake(
      _pid: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "updatePool(uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "updatePool(uint256,uint256,uint256)"(
      _pid: PromiseOrValue<BigNumberish>,
      _minDepositAmount: PromiseOrValue<BigNumberish>,
      _unstakeLockedBlocks: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    user(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAmount(
      _pid: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
